import { NextResponse } from 'next/server';
import pptxgen from 'pptxgenjs';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { title, subtitle, slides } = body;

    const pres = new pptxgen();
    pres.layout = 'LAYOUT_16x9';

    // Slide 1: Title Slide
    const slide1 = pres.addSlide();
    slide1.background = { color: '0F172A' }; // Dark slate background

    slide1.addText(title || 'Executive Presentation', {
      x: 0.8,
      y: 2.2,
      w: '80%',
      h: 1.2,
      fontSize: 32,
      bold: true,
      color: 'FFFFFF',
      fontFace: 'Arial',
    });

    slide1.addText(subtitle || 'Generated by Content Intelligence Platform', {
      x: 0.8,
      y: 3.6,
      w: '80%',
      h: 0.8,
      fontSize: 18,
      color: '94A3B8',
      fontFace: 'Arial',
    });

    // Subsequent content slides
    if (Array.isArray(slides)) {
      for (const slideData of slides) {
        const slide = pres.addSlide();
        slide.background = { color: 'FFFFFF' };

        // Top Header
        slide.addText(slideData.title || `Slide ${slideData.slideNumber}`, {
          x: 0.8,
          y: 0.6,
          w: '85%',
          h: 0.8,
          fontSize: 24,
          bold: true,
          color: '0F172A',
          fontFace: 'Arial',
        });

        // Main Content / Subtitle
        if (slideData.mainContent) {
          slide.addText(slideData.mainContent, {
            x: 0.8,
            y: 1.5,
            w: '85%',
            h: 0.8,
            fontSize: 14,
            italic: true,
            color: '475569',
            fontFace: 'Arial',
          });
        }

        // Bullet points
        if (Array.isArray(slideData.bulletPoints) && slideData.bulletPoints.length > 0) {
          const bullets = slideData.bulletPoints.map((b: string) => ({
            text: b,
            options: { bullet: true, fontSize: 13, color: '1E293B', lineSpacing: 24 },
          }));

          slide.addText(bullets, {
            x: 0.8,
            y: 2.5,
            w: '85%',
            h: 3.5,
            fontFace: 'Arial',
          });
        }

        // Speaker Notes
        if (slideData.speakerNotes) {
          slide.addNotes(slideData.speakerNotes);
        }
      }
    }

    const buffer = (await pres.write({ outputType: 'nodebuffer' })) as Buffer;
    const uint8 = new Uint8Array(buffer);

    return new Response(uint8, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="${encodeURIComponent(title || 'presentation')}.pptx"`,
      },
    });
  } catch (err: unknown) {
    console.error('PPTX export error:', err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'PPTX export failed' },
      { status: 500 }
    );
  }
}
